name: Build and push
on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest    
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build image
      run: |
        docker build . -t hello-gin

    - name: Setup aws elb cli
      uses: actions/aws/cli@master
      args: eb list -a
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
                