name: Build and push
on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest    
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    # - name: Build image
    #   run: |
    #     docker build . -t hello-gin

    - name: Setup aws elb cli
      run: |
        sudo apt-get clean && sudo apt-get update -y
        sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y git-core build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
        git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
        ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
        echo ${AWS_SECRET_ACCESS_KEY}